#!/bin/sh

out_dir=/Library/Logs/PaloAltoNetworks/GlobalProtect
app_dir=/Applications/GlobalProtect.app
install_dir=/Applications/GlobalProtect.app/Contents/Resources
support_dir="/Library/Application Support/PaloAltoNetworks/GlobalProtect"
mkdir -p "${support_dir}"
launchd_gps_path=/Library/LaunchAgents/com.paloaltonetworks.gp.pangps.plist
launchd_gps_deamon_path=/Library/LaunchDaemons/com.paloaltonetworks.gp.pangpsd.plist
launchd_gpa_path=/Library/LaunchAgents/com.paloaltonetworks.gp.pangpa.plist
old_user_defaults=/Library/Preferences/com.paloaltonetworks.GlobalProtect.plist
current_user_defaults=/Library/Preferences/com.paloaltonetworks.GlobalProtect.client.plist

generateLaunchctlPlist()
{
    printf "$1" > "$2"
    chown root:wheel "$2"
    chmod 0644 "$2"
}

checkAndWaitProcess()
{
    if [[ "$2" ]]; then
        T="$2"
    else
        T=5
    fi

    C=0
    while [[ C -lt $T ]] &&
          ( killall -s "$1" >/dev/null 2>/dev/null )
    do
        let C=C+1
        sleep 1
    done

    killall -s $1 >/dev/null 2>/dev/null
    return $?
}

pan_info()
{
    curtime=`date`
    echo $curtime " " $1 >> ${out_dir}/PanGPInstall.log
}

create_daemon_plist()
{
    daemon_plist='<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.paloaltonetworks.gp.pangps</string>
    <key>LimitLoadToSessionType</key>
    <string>Aqua</string>
    <key>Program</key>
    <string>/Applications/GlobalProtect.app/Contents/Resources/PanGPS</string>
    <key>WorkingDirectory</key>
    <string>/Applications/GlobalProtect.app/Contents/Resources</string>
    <key>RunAtLoad</key>
    <true/>
    <key>ExitTimeOut</key>
    <integer>20</integer>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
</dict>
</plist>'
    generateLaunchctlPlist "$daemon_plist" "$launchd_gps_path"

    daemon_plistd='<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.paloaltonetworks.gp.pangpsd</string>
    <key>Program</key>
    <string>/Applications/GlobalProtect.app/Contents/Resources/PanGPS</string>
    <key>WorkingDirectory</key>
    <string>/Applications/GlobalProtect.app/Contents/Resources</string>
    <key>RunAtLoad</key>
    <true/>
    <key>ExitTimeOut</key>
    <integer>20</integer>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
</dict>
</plist>'
    generateLaunchctlPlist "$daemon_plistd" "$launchd_gps_deamon_path"
}

create_agent_plist()
{
    agent_plist='<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.paloaltonetworks.gp.pangpa</string>
    <key>LimitLoadToSessionType</key>
    <string>Aqua</string>
    <key>Program</key>
    <string>/Applications/GlobalProtect.app/Contents/MacOS/GlobalProtect</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>'
    generateLaunchctlPlist  "$agent_plist" "$launchd_gpa_path"
}

((
    if [[ "$HOME" ]]; then
        PKG_OWNER=`stat -f "%Su" "$HOME"`
    else
        PKG_OWNER=`stat -f "%Su" "$PACKAGE_PATH"`
    fi

    osver_major=$(sw_vers -productVersion | cut -d'.' -f1)
    osver_minor=$(sw_vers -productVersion | cut -d'.' -f2)
    osver_bugfix=$(sw_vers -productVersion | cut -d'.' -f3)
    isElCaptionNewer=0
    if { [ $osver_major -gt 10 ]; } || { { [ $osver_major -eq 10 ]; } && { [ $osver_minor -gt 10 ];  } }; then
       isElCaptionNewer=1
       pan_info "MacOS version $osver_major.$osver_minor.$osver_bugfix"
    else
      pan_info "MacOS version $osver_major.$osver_minor.$osver_bugfix older than El Caption"
    fi

    loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }' )
    CONSOLE_USER=`stat -f "%Su" /dev/console`
    run_as_console_user=1
    pan_info "postinstall get current logged-in user ${loggedInUser}"
    pan_info "postinstall get current console user ${CONSOLE_USER}"
    console_user_id=`id -u ${loggedInUser}`
    pan_info "postinstall get current user ${PKG_OWNER}"
    if [ -z $loggedInUser ] && [ $CONSOLE_USER = "root" ]; then
        pan_info "postinstall run without console"
        run_as_console_user=0
    fi
    pan_info "console user id $console_user_id"
    pan_info "Setting up GlobalProtect, user $CONSOLE_USER"
    pan_info "Arguments $@"
    id
    sudo -u"$CONSOLE_USER" launchctl list|grep paloalto

    #change file owner permission
    chown -R root:wheel ${app_dir}
    chmod -R 0755 ${install_dir}/pangpd.kext
    chmod -R 0755 ${install_dir}/gplock.kext
    chmod -R 0755 ${install_dir}/gpsplit.kext
    chmod -R 0755 ${install_dir}/gpsplit-helper
    chmod 4755 ${install_dir}/PanGPS

	# #This is a workaround for macOS 10.13 kextcache out of sync issue
	# pan_info "Verify kexts"
	# if ! kextutil -tn -v 3  ${install_dir}/pangpd.kext
	# then
	# 	pan_info "Clearing kext staging"
	# 	kextcache -clear-staging -v 4
	# 	pan_info "Rebuild kext cache"
	# 	kextcache -invalidate / -v 4
	# 	pan_info "Forced update for system kext cache"
	# 	kextutil -tn -v 5  ${install_dir}/pangpd.kext
	# fi


    pan_info "Removing launchd jobs"
    rm -f $launchd_gpa_path
    rm -f $launchd_gps_path
    rm -f $launchd_gps_deamon_path

    pan_info "removing com.paloaltonetworks.gp.pangpa"
    launchctl remove com.paloaltonetworks.gp.pangpa

    pan_info "removing com.paloaltonetworks.gp.pangps"
    launchctl remove com.paloaltonetworks.gp.pangps

    pan_info "removing com.paloaltonetworks.gp.pangpsd"
    launchctl remove com.paloaltonetworks.gp.pangpsd

    if [[ "$PKG_OWNER" != "daemon" ]]; then
      pan_info "removing $CONSOLE_USER com.paloaltonetworks.gp.pangpa"
      sudo -u"$CONSOLE_USER" launchctl remove com.paloaltonetworks.gp.pangpa

      pan_info "removing $CONSOLE_USER com.paloaltonetworks.gp.pangps"
      sudo -u"$CONSOLE_USER" launchctl remove com.paloaltonetworks.gp.pangps

      pan_info "removing $CONSOLE_USER com.paloaltonetworks.gp.pangpsd"
      sudo -u"$CONSOLE_USER" launchctl remove com.paloaltonetworks.gp.pangpsd
    fi

    #wait for 90 sec. while PanGPS quits
    if checkAndWaitProcess "PanGPS" 90; then
        pan_info "PanGPS didn't quit within 90 sec. Killing"
        killall -9 PanGPS
        if checkAndWaitProcess "PanGPS" 30; then
            pan_info "PanGPS didn't quit after kill -9 within 30 sec."
        fi
    fi

    ifconfig gpd0 down
    kextstat -b com.paloaltonetworks.GlobalProtect.gplock | grep com.paloaltonetworks.GlobalProtect.gplock | grep -v grep > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        pan_info "Unloading enforcer"
        kextunload -b com.paloaltonetworks.GlobalProtect.gplock
    fi
    kextstat -b com.paloaltonetworks.kext.pangpd | grep com.paloaltonetworks.kext.pangpd | grep -v grep > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        pan_info "Unloading virtual adapter"
        kextunload -b com.paloaltonetworks.kext.pangpd
    fi

    if [ -f ${out_dir}/enforcer.loaded ]; then
        rm -f ${out_dir}/enforcer.loaded
        pan_info "Copy enforcer to system folder"
        cp -Rf ${install_dir}/gplock.kext /Library/Extensions/
    fi

    if [ -f "/Applications/GlobalProtect.app/Contents/Resources/DEM.pkg" ]; then
        pan_info "Copy dem.pkg to /Library/Application Support/PaloAltoNetworks/GlobalProtect"
        cp -f "/Applications/GlobalProtect.app/Contents/Resources/DEM.pkg" "/Library/Application Support/PaloAltoNetworks/GlobalProtect/DEM.pkg"
    fi

    use_utun=0
    osver_major=$(sw_vers -productVersion | cut -d'.' -f1)
    osver_minor=$(sw_vers -productVersion | cut -d'.' -f2)
    osver_bugfix=$(sw_vers -productVersion | cut -d'.' -f3)
    pan_info "current macOS version $osver_major.$osver_minor.$osver_bugfix"
    if { [ $osver_major -gt 10 ]; } || { { [ $osver_major -eq 10 ]; } && { [ $osver_minor -gt 15 ] || { [ $osver_minor -eq 15 ] && [ $osver_bugfix -ge 4 ]; }; } }; then
        pan_info "use utun"
        use_utun=1
    fi

    if [ $use_utun -eq 0 ]; then
        #This is a workaround for macOS 10.13 kextcache out of sync issue
        pan_info "Verify virtual adapter"
        if ! kextutil -tn -v 3  ${install_dir}/pangpd.kext
        then
            pan_info "Clearing kext staging"
            kextcache -clear-staging -v 4
            pan_info "Rebuild kext cache"
            kextcache -invalidate / -v 4
            pan_info "Forced update for system kext cache"
            kextutil -tn -v 5  ${install_dir}/pangpd.kext
        fi
    fi

    #copy old user defaults when updating from 5.0.x and below
    if [[ "$HOME" ]] && [ -f "$HOME"${old_user_defaults} ] && [ ! -f "$HOME"${current_user_defaults} ]; then
        cp -p "$HOME"${old_user_defaults} "$HOME"${current_user_defaults}
        sudo chmod +rw "$HOME"${current_user_defaults}
        rm "$HOME"${old_user_defaults}
    fi

    CONSOLE_USER=$(stat -f "%Su" /dev/console)
    CONSOLE_GRP=$(stat -f "%Sg" /dev/console)

    if [[ "$HOME" ]] && [ -f "$HOME"${old_user_defaults} ] ; then
        FILE_USER=$(stat -f "%Su" "$HOME"${old_user_defaults})
        FILE_GRP=$(stat -f "%Sg" "$HOME"${old_user_defaults})
        pan_info "old_user_defaults permission is $FILE_USER:$FILE_GRP"
        if [ "$FILE_USER" != "$CONSOLE_USER" ] || [ "$FILE_GRP" != "$CONSOLE_GRP" ] ; then
            pan_info "Change old_user_defaults permission to $CONSOLE_USER:$CONSOLE_GRP"
            sudo chown $CONSOLE_USER:$CONSOLE_GRP "$HOME"${old_user_defaults}
        fi
    else
        if [[ "$HOME" ]] && [ -f "$HOME"${current_user_defaults} ] ; then
            FILE_USER=$(stat -f "%Su" "$HOME"${current_user_defaults})
            FILE_GRP=$(stat -f "%Sg" "$HOME"${current_user_defaults})
            pan_info "current_user_defaults permission is $FILE_USER:$FILE_GRP"
            if [ "$FILE_USER" != "$CONSOLE_USER" ] || [ "$FILE_GRP" != "$CONSOLE_GRP" ] ; then
                pan_info "Change current_user_defaults permission to $CONSOLE_USER:$CONSOLE_GRP"
                sudo chown $CONSOLE_USER:$CONSOLE_GRP "$HOME"${current_user_defaults}
            fi
        fi
    fi

    echo "remove State:/Network/Service/gpd.pan/IPv4" | scutil
    echo "remove State:/Network/Service/gpd.pan/DNS"  | scutil

    pan_info "install daemon plist"
    create_daemon_plist

    pan_info "install agent plist"
    create_agent_plist

    killall -15 GlobalProtect
    if [[ "$PKG_OWNER" = "daemon" ]]; then
        pan_info "load gps daemon"
        launchctl load $launchd_gps_deamon_path
    else
      if [ $run_as_console_user -eq 1 ]; then
          pan_info "Load gps and gpa as console user $CONSOLE_USER"
          #if [ $isElCaptionNewer -eq 1 ]; then
            launchctl bootstrap gui/$console_user_id $launchd_gps_path
            launchctl bootstrap gui/$console_user_id $launchd_gpa_path
          #else
          #  sudo -u"$CONSOLE_USER" launchctl load -S Aqua -w $launchd_gps_path
          #  sudo -u"$CONSOLE_USER" launchctl load -S Aqua -w $launchd_gpa_path
          #fi
      else
          pan_info "Load gps and gpa as user $CONSOLE_USER"
          #launchctl bootstrap gui/$console_user_id $launchd_gps_path
          #launchctl bootstrap gui/$console_user_id $launchd_gpa_path
          sudo -u"$CONSOLE_USER" launchctl load -S Aqua -w $launchd_gps_path
          sudo -u"$CONSOLE_USER" launchctl load -S Aqua -w $launchd_gpa_path
      fi
    fi

    pan_info "Removing old GlobalProtect"
    rm -rf "/Applications/GlobalProtect.app.bak"

    if [[ "$COMMAND_LINE_INSTALL" ]]; then
        pan_info "Removing $PACKAGE_PATH"
        rm -f "$PACKAGE_PATH"
    fi


) 2>&1) >> ${out_dir}/PanGPInstall.log


pan_info "GlobalProtect installation finished."
